MLK-15098: ASoC: fsl: fix imx-pcm build error when no dma
Fix build error when SOC_IMX_PCM_DMA is not enabled
error: expected identifier or ‘(’ before ‘{’ token})

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
(cherry picked from commit 67ee27e3c97c8deb851ca61fab0e513009b93dbe)
[zou:Original patch taken from
git://git.freescale.com/imx/linux-imx.git imx_4.9.11_1.0.0_ga]
Signed-off-by: zou cao <cao.zou@windriver.com>