gpu: fix compile error with header file nmi.h
In upstream commit d151b27d3f86 ("sched/headers: Move softlockup detector
watchdog methods to <linux/nmi.h>"), the function "touch_softlockup_watchdog"
has been moved to "include/linux/nmi.h", so add header file to avoid building
error as below:

drivers/mxc/gpu-viv/hal/kernel/gc_hal_kernel_debug.c:622:5: error: implicit declaration of function ‘touch_softlockup_watchdog’ [-Werror=implicit-function-declaration]
     gcmkOUTPUT_STRING(buffer);
     ^

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>