MLK-11065-8 bcmdhd: fixed build errors with 3.9.2 toolchain
  CC [M]  drivers/net/wireless/bcmdhd/dhd_ip.o
  LD [M]  fs/udf/udf.o
drivers/net/wireless/bcmdhd/dhd_common.c:108:22: error: macro "__DATE__" might prevent reproducible builds [-Werror=date-time]
  DHD_COMPILED " on " __DATE__ " at " __TIME__;
                      ^
drivers/net/wireless/bcmdhd/dhd_common.c:108:38: error: macro "__TIME__" might prevent reproducible builds [-Werror=date-time]
  DHD_COMPILED " on " __DATE__ " at " __TIME__;

Drop debug version with build date/time.
The kernel already has this information, and individual drivers
shouldn't duplicate that.  This also eliminates the use of __DATE__ and
__TIME__, which make the build non-deterministic.

Signed-off-by: Dong Aisheng <b29396@freescale.com>
(cherry picked from commit 3f47e9588c8acf5c4cc5079e746bc05e7d5c69ec)
[zou:Original patch taken from
git://git.freescale.com/imx/linux-imx.git imx_4.9.11_1.0.0_ga]
Signed-off-by: zou cao <cao.zou@windriver.com>