gpu-viv: fix build error with signal header file
In upstream commit c3edc4010e9d ("sched/headers: Move task_struct::signal
and task_struct::sighand types and accessors into <linux/sched/signal.h>"),
the function "send_sig_info" has been moved to linux/sched/signal.h.
In upstream commit 2a1f062a4acf ("sched/headers: Move signal wakeup &
sigpending methods from <linux/sched.h> into <linux/sched/signal.h>"),
the function "signal_pending" has been moved to linux/sched/signal.h.

so add new header file to fix building error as below:

drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c: In function ‘gckOS_SetSignalVG’:
drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:5920:9: error: implicit declaration of function ‘send_sig_info’ [-Werror=implicit-function-declaration]
         result = send_sig_info(48, &info, userTask);
         ^
drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c: In function ‘gckOS_WaitSignal’:
drivers/mxc/gpu-viv/hal/os/linux/kernel/gc_hal_kernel_os.c:6083:13: error: implicit declaration of function ‘signal_pending’ [-Werror=implicit-function-declaration]
             if (Interruptable && signal_pending(current))
             ^

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>